version: '3.7'
services:
  node-app:
    container_name: raccoon-server
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: "${DB_PORT:-3306}"  # Define 3306 como valor padrão
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: db
    image: 'mysql/mysql-server:8.0'
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    ports:
      - "${DB_PORT:-3306}:3306"  # Define 3306 como valor padrão
