version: '3.7'
services:
  node-app:
    container_name: raccoon-server
    build:
      context: .  # Isso vai usar o Dockerfile na pasta atual
    ports:
      - "4000:4000"
    volumes:
      - ./public:/app/public
    environment:
      DB_HOST: ${DB_HOST}  # Nome do serviço do banco de dados
      DB_PORT: "${DB_PORT:-3306}"  # Define 3306 como valor padrão
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    env_file:
      - .env  # Variáveis de ambiente adicionais
    networks:
      - global-db-network  # Garantindo que ambos os containers estão na mesma rede

networks:
  global-db-network:
    external: true
