name: deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server
      run: |
        ssh root@0.6.193.168 "cd ~/containers/node/raccoontech && git pull origin main"